repositories:
  remote:
   - http://repo1.maven.org/maven2

artifacts:
  getopt4j: org.realityforge.getopt4j:getopt4j:jar:1.2
  postgresql: postgresql:postgresql:jar:9.1-901.jdbc4
  jtds: net.sourceforge.jtds:jtds:jar:1.2.7
  diffutils: com.googlecode.java-diff-utils:diffutils:jar:1.2.1
