repositories:
  remote:
   - http://repo.fire.dse.vic.gov.au/content/groups/fisg
   - http://repo1.maven.org/maven2

artifacts:
  spice_cli: spice:spice-cli:jar:1.0
  postgresql: postgresql:postgresql:jar:9.1-901.jdbc4
  jtds: net.sourceforge.jtds:jtds:jar:1.2.5
  diffutils: com.googlecode.java-diff-utils:diffutils:jar:1.2.1
